version: '3'

services:
  fastapi:
    restart: always
    image: service-data-eda-analysis
    ports:
      - '8002:8000'
    env_file:
      - docker/.env
    volumes:
      - /workspace/data:/home/app/workdir/data/